services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.dorbenabu.com
    domainname: dorbenabu.com
    env_file: ./docker-data/dms/config/mailserver.env
    ports:
      - "25:25"     # SMTP (STARTTLS)
      - "143:143"   # IMAP (STARTTLS)
      - "465:465"   # SMTP (implicit TLS)
      - "587:587"   # SMTP (explicit TLS)
      - "993:993"   # IMAP (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/live/mail.dorbenabu.com/fullchain.pem:/tmp/docker-mailserver/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/mail.dorbenabu.com/privkey.pem:/tmp/docker-mailserver/ssl/privkey.pem:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --ipv4 --tcp | grep --silent ':smtp' || exit 1"
      timeout: 3s
      retries: 0
