version: '3.8'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: dorbenabu.com
    restart: always
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "465:465"
    volumes:
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/dms/config/ssl/fullchain.pem:/tmp/docker-mailserver/ssl/fullchain.pem:ro
      - ./docker-data/dms/config/ssl/privkey.pem:/tmp/docker-mailserver/ssl/privkey.pem:ro
    environment:
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/docker-mailserver/ssl/fullchain.pem
      - SSL_KEY_PATH=/tmp/docker-mailserver/ssl/privkey.pem
      - ENABLE_FAIL2BAN=1
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - PERMIT_DOCKER=host
      - LOG_LEVEL=info
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    stop_grace_period: 1m
